### ISSUE TITLE
README.md에 관해

### ISSUE THREAD

**Issue by Namnamseo** [hletrd/koistudy2#15]
1)
http://stackoverflow.com/questions/3220404/why-use-pip-over-easy-install/3220572#3220572
easy_install 대신에 pip를 쓰는 게 나아요.

2)
Ubuntu의 MongoDB의 경우 저는 sudo apt-get install mongodb 한 번으로 해결했어요.

3)
py-bcrypt가 Windows에서 잘 설치가 안 되어서 호환되는 bcrypt로 바꾸는게 나을 것 같네요.
bcrypt는 pip로 설치할 수 있어요.

4)
mongod는 아마 MongoDB를 설치하면 서비스 형태로 자동으로 실행될 거예요.

**Comment by Namnamseo** [comment]
Ubuntu에서 자체적으로 제공하는 mongodb 패키지가 있고,
MongoDB에서 제공하는 mongodb-org 패키지가 있네요.
후자가 조금 더 최신이라고 합니다

**Comment by hletrd** [comment]
1) 바꿔주세여
2) CentOS 같은 경우 기본 repo에는 mongodb 2.4, MongoDB repo에는 3.0이 있음. 근데 CentOS 같은 경우 기본 repo의 mongodb 2.4는 MariaDB에서 사용하는 boost 패키지보다 구 버전을 사용하기 때문에 꼬여서 mongodb-org로 설치하는 걸 권장.
3) 바꿔주세여
4) chkconfig mongod on 하고 service start mongod 해도 되고, 그냥 mongod 해도 됨. 나 같은 경우 전자로 했음

**Comment by hletrd** [comment]
끝난 것 같네여
