### ISSUE TITLE
/usr/share/nginx/html/koistudy2/login.py:11: DeprecationWarning: the md5 module is deprecated; use hashlib instead   import md5

### ISSUE THREAD

**Issue by hletrd** [hletrd/koistudy2#21]
/usr/share/nginx/html/koistudy2/login.py:11: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5

**Comment by ho94949** [comment]
Closed at 242f21a63f24afc8bb17426cac05c2dde08ee12c
